name: octoread_engine
description: OctoRead Engine
version: 0.0.1
author: Anar K. Jafarov <anar.k.jafarov@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.3.0
  yaml: ^2.2.0

dev_dependencies:
  test: ^1.0.0